import Joi from "joi";

export const createMovieSchema = Joi.object({
  title: Joi.string().min(1).max(255).required(),
  slug: Joi.string().min(1).max(255).optional(),
  description: Joi.string().optional(),
  short_description: Joi.string().optional(),
  thumbnail_url: Joi.string().uri().optional(),
  poster_url: Joi.string().uri().optional(),
  banner_url: Joi.string().uri().optional(),
  trailer_url_type: Joi.string().valid("youtube", "vimeo", "mp4", "hls").optional(),
  trailer_url: Joi.string().uri().optional(),
  streams: Joi.array()
    .items(
      Joi.object({
        label: Joi.string().optional(),
        type: Joi.string().optional(),
        url: Joi.string().uri().required(),
      }),
    )
    .optional(),
  access_type: Joi.string().valid("free", "subscription", "pay_per_view").optional(),
  plan_ids: Joi.array().items(Joi.string()).optional(),
  pay_per_view_price: Joi.number().min(0).optional(),
  purchase_type: Joi.string().valid("rent", "buy").optional(),
  access_duration_hours: Joi.number().min(0).optional(),
  language: Joi.string().optional(),
  imdb_rating: Joi.number().min(0).max(10).optional(),
  content_rating: Joi.string().optional(),
  release_date: Joi.date().optional(),
  duration_minutes: Joi.number().min(0).optional(),
  genres: Joi.array().items(Joi.string()).optional(),
  cast: Joi.array().items(Joi.string()).optional(),
  directors: Joi.array().items(Joi.string()).optional(),
  tags: Joi.array().items(Joi.string()).optional(),
  is_premium: Joi.boolean().optional(),
  is_featured: Joi.boolean().optional(),
  is_trending: Joi.boolean().optional(),
  is_coming_soon: Joi.boolean().optional(),
  is_downloadable: Joi.boolean().optional(),
  seo_title: Joi.string().optional(),
  seo_description: Joi.string().optional(),
  seo_keywords: Joi.array().items(Joi.string()).optional(),
  status: Joi.string().valid("draft", "published").optional(),
});

export const updateMovieSchema = Joi.object({
  title: Joi.string().min(1).max(255).optional(),
  slug: Joi.string().min(1).max(255).optional(),
  description: Joi.string().optional(),
  short_description: Joi.string().optional(),
  thumbnail_url: Joi.string().uri().optional(),
  poster_url: Joi.string().uri().optional(),
  banner_url: Joi.string().uri().optional(),
  trailer_url_type: Joi.string().valid("youtube", "vimeo", "mp4", "hls").optional(),
  trailer_url: Joi.string().uri().optional(),
  streams: Joi.array()
    .items(
      Joi.object({
        label: Joi.string().optional(),
        type: Joi.string().optional(),
        url: Joi.string().uri().required(),
      }),
    )
    .optional(),
  access_type: Joi.string().valid("free", "subscription", "pay_per_view").optional(),
  plan_ids: Joi.array().items(Joi.string()).optional(),
  pay_per_view_price: Joi.number().min(0).optional(),
  purchase_type: Joi.string().valid("rent", "buy").optional(),
  access_duration_hours: Joi.number().min(0).optional(),
  language: Joi.string().optional(),
  imdb_rating: Joi.number().min(0).max(10).optional(),
  content_rating: Joi.string().optional(),
  release_date: Joi.date().optional(),
  duration_minutes: Joi.number().min(0).optional(),
  genres: Joi.array().items(Joi.string()).optional(),
  cast: Joi.array().items(Joi.string()).optional(),
  directors: Joi.array().items(Joi.string()).optional(),
  tags: Joi.array().items(Joi.string()).optional(),
  is_premium: Joi.boolean().optional(),
  is_featured: Joi.boolean().optional(),
  is_trending: Joi.boolean().optional(),
  is_coming_soon: Joi.boolean().optional(),
  is_downloadable: Joi.boolean().optional(),
  seo_title: Joi.string().optional(),
  seo_description: Joi.string().optional(),
  seo_keywords: Joi.array().items(Joi.string()).optional(),
  status: Joi.string().valid("draft", "published").optional(),
}).min(1);

export const paginatedMoviesSchema = Joi.object({
  page: Joi.number().integer().min(1).optional().default(1),
  limit: Joi.number().integer().min(1).max(100).optional().default(10),
  sort: Joi.string().optional().default("updatedAt"),
  order: Joi.string().valid("ASC", "DESC").optional().default("DESC"),
  genre: Joi.string().optional().allow("", null),
  year: Joi.number().integer().min(1900).max(2100).optional(),
  access_type: Joi.string().valid("free", "subscription", "pay_per_view").optional(),
  is_featured: Joi.boolean().optional(),
  is_trending: Joi.boolean().optional(),
  is_coming_soon: Joi.boolean().optional(),
  search: Joi.string().optional(),
});

